let default_decks = [
	{
		"title": "默认北方领域卡组 1",
		"description": "待定",
		"leader": "nr_foltest_siegemaster",
		"faction": "realms",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 3],
			["spe_frost", 1],
			["ntr_ciri", 1],
			["ntr_geralt", 1],
			["nr_esterad", 1],
			["nr_natalis", 1],
			["nr_philippa", 1],
			["nr_vernon", 1],
			["nr_catapult_1", 1],
			["nr_catapult_2", 1],
			["ntr_triss", 1],
			["ntr_villen", 1],
			["ntr_yennefer", 1],
			["nr_ballista", 1],
			["ntr_olgierd", 1],
			["nr_siege_tower", 1],
			["nr_trebuchet", 1],
			["nr_trebuchet_1", 1],
			["nr_crinfrid_1", 1],
			["nr_crinfrid_2", 1],
			["nr_crinfrid_3", 1],
			["nr_banner_nurse", 1],
			["nr_stennis", 1],
			["nr_blue_stripes_1", 1],
			["nr_blue_stripes_2", 1],
			["nr_blue_stripes_3", 1],
			["ntr_gaunter_odimm_darkness", 3],
			["nr_dijkstra", 1],
			["ntr_dandelion", 1],
			["ntr_gaunter_odimm", 1],
			["nr_thaler", 1],
			["ntr_mysterious_elf", 1]
		]
	},
	{
		"title": "默认北方领域卡组 2",
		"description": "待定",
		"leader": "nr_foltest_siegemaster",
		"faction": "realms",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 3],
			["spe_frost", 1],
			["spe_clear", 1],
			["spe_fog", 1],
			["spe_rain", 1],
			["ntr_ciri", 1],
			["ntr_geralt", 1],
			["nr_esterad", 1],
			["nr_natalis", 1],
			["nr_philippa", 1],
			["nr_vernon", 1],
			["nr_catapult_1", 1],
			["nr_catapult_2", 1],
			["ntr_triss", 1],
			["ntr_villen", 1],
			["ntr_yennefer", 1],
			["nr_ballista", 1],
			["ntr_olgierd", 1],
			["nr_siege_tower", 1],
			["nr_trebuchet", 1],
			["nr_trebuchet_1", 1],
			["nr_crinfrid_1", 1],
			["nr_crinfrid_2", 1],
			["nr_crinfrid_3", 1],
			["nr_banner_nurse", 1],
			["nr_stennis", 1],
			["nr_blue_stripes_1", 1],
			["nr_blue_stripes_2", 1],
			["nr_blue_stripes_3", 1],
			["ntr_gaunter_odimm_darkness", 3],
			["nr_dijkstra", 1],
			["ntr_dandelion", 1],
			["ntr_gaunter_odimm", 1],
			["nr_thaler", 1],
			["ntr_mysterious_elf", 1]
		]
	},
	{
		"title": "默认尼弗迦德卡组 1",
		"description": "待定",
		"leader": "ne_emhyr_relentless",
		"faction": "nilfgaard",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 3],
			["spe_scorch", 1],
			["spe_frost", 1],
			["spe_clear", 1],
			["spe_fog", 1],
			["spe_rain", 1],
			["ntr_ciri", 1],
			["ntr_geralt", 1],
			["ne_black_archer", 1],
			["ne_black_archer_1", 1],
			["ne_heavy_zerri", 1],
			["ne_menno", 1],
			["ne_moorvran", 1],
			["ne_stefan", 1],
			["ne_shilard", 1],
			["ntr_villen", 1],
			["ntr_yennefer", 1],
			["ntr_olgierd", 1],
			["ne_young_emissary_1", 1],
			["ne_young_emissary_2", 1],
			["ntr_gaunter_odimm_darkness", 3],
			["ne_vattier", 1],
			["ne_impera_brigade_1", 1],
			["ne_impera_brigade_2", 1],
			["ne_impera_brigade_3", 1],
			["ne_impera_brigade_4", 1],
			["ntr_dandelion", 1],
			["ntr_gaunter_odimm", 1],
			["ne_archer_support", 1],
			["ne_archer_support_1", 1],
			["ntr_mysterious_elf", 1],
			["ne_siege_support", 1]
		]
	},
	{
		"title": "默认尼弗迦德卡组 2",
		"description": "待定",
		"leader": "ne_emhyr_whiteflame",
		"faction": "nilfgaard",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 3],
			["spe_scorch", 2],
			["spe_clear", 1],
			["spe_fog", 1],
			["spe_rain", 1],
			["ntr_ciri", 1],
			["ntr_geralt", 1],
			["ne_black_archer", 1],
			["ne_black_archer_1", 1],
			["ne_heavy_zerri", 1],
			["ne_menno", 1],
			["ne_moorvran", 1],
			["ntr_villen", 1],
			["ntr_yennefer", 1],
			["ne_assire", 1],
			["ne_cahir", 1],
			["ne_fringilla", 1],
			["ntr_olgierd", 1],
			["ntr_vesemir", 1],
			["ne_young_emissary_1", 1],
			["ne_young_emissary_2", 1],
			["ne_vattier", 1],
			["ne_impera_brigade_1", 1],
			["ne_impera_brigade_2", 1],
			["ne_impera_brigade_3", 1],
			["ne_impera_brigade_4", 1],
			["ntr_dandelion", 1],
			["ne_archer_support", 1],
			["ne_archer_support_1", 1],
			["ntr_cow", 1],
			["ntr_mysterious_elf", 1],
			["ne_siege_support", 1]
		]
	},
	{
		"title": "默认怪物卡组 1",
		"description": "待定",
		"leader": "mo_eredin_commander",
		"faction": "monsters",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 3],
			["spe_scorch", 1],
			["spe_clear", 1],
			["spe_fog", 1],
			["spe_rain", 1],
			["ntr_ciri", 1],
			["ntr_geralt", 1],
			["mo_imlerith", 1],
			["mo_kayran", 1],
			["mo_toad", 1],
			["ntr_villen", 1],
			["ntr_yennefer", 1],
			["mo_arachas_behemoth", 1],
			["mo_witch_velen", 1],
			["mo_witch_velen_1", 1],
			["mo_witch_velen_2", 1],
			["ntr_olgierd", 1],
			["mo_katakan", 1],
			["mo_arachas", 1],
			["mo_arachas_1", 1],
			["mo_arachas_2", 1],
			["mo_botchling", 1],
			["ntr_gaunter_odimm_darkness", 3],
			["mo_bruxa", 1],
			["mo_ekkima", 1],
			["mo_fleder", 1],
			["mo_garkain", 1],
			["ntr_dandelion", 1],
			["ntr_gaunter_odimm", 1],
			["mo_nekker", 1],
			["mo_nekker_1", 1],
			["mo_nekker_2", 1],
			["ntr_mysterious_elf", 1]
		]
	},
	{
		"title": "默认怪物卡组 2",
		"description": "待定",
		"leader": "mo_eredin_bringer_of_death",
		"faction": "monsters",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 1],
			["spe_scorch", 3],
			["spe_clear", 1],
			["spe_fog", 1],
			["spe_rain", 1],
			["ntr_ciri", 1],
			["ntr_geralt", 1],
			["mo_kayran", 1],
			["ntr_villen", 1],
			["ntr_yennefer", 1],
			["mo_arachas_behemoth", 1],
			["mo_witch_velen", 1],
			["mo_witch_velen_1", 1],
			["mo_witch_velen_2", 1],
			["ntr_olgierd", 1],
			["mo_katakan", 1],
			["mo_arachas", 1],
			["mo_arachas_1", 1],
			["mo_arachas_2", 1],
			["ntr_gaunter_odimm_darkness", 3],
			["mo_bruxa", 1],
			["mo_ekkima", 1],
			["mo_fleder", 1],
			["mo_garkain", 1],
			["ntr_mysterious_elf", 1]
		]
	},
	{
		"title": "默认松鼠党卡组 1",
		"description": "待定",
		"leader": "sc_francesca_daisy",
		"faction": "scoiatael",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 3],
			["spe_scorch", 1],
			["spe_frost", 1],
			["spe_clear", 1],
			["spe_fog", 1],
			["spe_rain", 1],
			["ntr_ciri", 1],
			["ntr_geralt", 1],
			["sc_isengrim", 1],
			["sc_milva", 1],
			["sc_schirru", 1],
			["ntr_villen", 1],
			["ntr_yennefer", 1],
			["sc_dol_infantry", 1],
			["ntr_olgierd", 1],
			["sc_havekar_support", 1],
			["sc_havekar_support_1", 1],
			["sc_havekar_support_2", 1],
			["ntr_gaunter_odimm_darkness", 3],
			["sc_ciaran", 1],
			["sc_dwarf", 1],
			["sc_dwarf_1", 1],
			["sc_dwarf_2", 1],
			["ntr_dandelion", 1],
			["ntr_gaunter_odimm", 1],
			["sc_havekar_nurse", 1],
			["sc_havekar_nurse_1", 1],
			["ntr_mysterious_elf", 1]
		]
	},
	{
		"title": "默认松鼠党卡组 2",
		"description": "待定",
		"leader": "sc_francesca_hope_of_the_aen_seidhe",
		"faction": "scoiatael",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 3],
			["spe_scorch", 1],
			["spe_frost", 1],
			["spe_clear", 1],
			["spe_fog", 1],
			["spe_rain", 1],
			["ntr_ciri", 1],
			["ntr_geralt", 1],
			["sc_isengrim", 1],
			["sc_milva", 1],
			["sc_schirru", 1],
			["ntr_villen", 1],
			["ntr_yennefer", 1],
			["sc_dol_infantry", 1],
			["sc_dol_infantry_1", 1],
			["sc_dol_infantry_2", 1],
			["sc_filavandrel", 1],
			["ntr_olgierd", 1],
			["sc_havekar_support", 1],
			["sc_havekar_support_1", 1],
			["sc_havekar_support_2", 1],
			["ntr_gaunter_odimm_darkness", 3],
			["ntr_dandelion", 1],
			["ntr_gaunter_odimm", 1],
			["ntr_cow", 1],
			["sc_havekar_nurse", 1],
			["sc_havekar_nurse_1", 1],
			["ntr_mysterious_elf", 1]
		]
	},
	{
		"title": "默认史凯利格卡组 1",
		"description": "待定",
		"leader": "sk_crach_an_craite",
		"faction": "skellige",
		"cards": [
			["spe_horn", 1],
			["spe_mardroeme", 1],
			["spe_scorch", 1],
			["spe_frost", 1],
			["spe_storm", 1],
			["spe_rain", 1],
			["ntr_ciri", 1],
			["ntr_geralt", 1],
			["sk_olaf", 1],
			["sk_cerys", 1],
			["sk_ermion", 1],
			["ntr_villen", 1],
			["ntr_yennefer", 1],
			["sk_craite_warrior_1", 1],
			["sk_craite_warrior_2", 1],
			["sk_craite_warrior_3", 1],
			["sk_dimun_pirate", 1],
			["ntr_olgierd", 1],
			["sk_shield_maiden_1", 1],
			["sk_shield_maiden_2", 1],
			["sk_shield_maiden_3", 1],
			["sk_light_longship", 3],
			["sk_birna", 1],
			["ntr_dandelion", 1],
			["sk_young_berserker", 3],
			["sk_kambi", 1],
			["ntr_mysterious_elf", 1]
		]
	},
	{
		"title": "默认史凯利格卡组 2",
		"description": "待定",
		"leader": "sk_crach_an_craite",
		"faction": "skellige",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["ntr_ciri", 1],
			["ntr_geralt", 1],
			["sk_olaf", 1],
			["sk_cerys", 1],
			["ntr_villen", 1],
			["sk_craite_warrior_1", 1],
			["sk_craite_warrior_2", 1],
			["sk_craite_warrior_3", 1],
			["sk_dimun_pirate", 1],
			["ntr_olgierd", 1],
			["sk_war_longship_1", 1],
			["sk_war_longship_2", 1],
			["sk_shield_maiden_1", 1],
			["sk_shield_maiden_2", 1],
			["sk_shield_maiden_3", 1],
			["ntr_gaunter_odimm_darkness", 3],
			["sk_light_longship", 3],
			["sk_birna", 1],
			["ntr_mysterious_elf", 1]
		]
	}
];

var custom_decks = [
	{
		"title": "北方领域 - 泰莫利亚",
		"description": "以泰莫利亚卡牌为核心的北方领域卡组 - 打法：紧密羁绊、间谍",
		"leader": "nr_foltest_lord",
		"faction": "realms",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 1],
			["spe_fog", 1],
			["spe_scorch", 1],
			["nr_esterad", 1],
			["nr_natalis", 1],
			["ntr_triss", 1],
			["nr_vernon", 1],
			["nr_ballista", 1],
			["nr_siege_tower", 1],
			["nr_trebuchet_1", 1],
			["nr_blue_stripes_skirmisher_1", 1],
			["nr_blue_stripes_skirmisher_2", 1],
			["nr_blue_stripes_skirmisher_3", 1],
			["nr_blue_stripes_1", 1],
			["nr_blue_stripes_2", 1],
			["nr_blue_stripes_3", 1],
			["nr_dijkstra", 1],
			["nr_thaler", 1],
			["nr_temerian_soldier_1", 1],
			["nr_temerian_soldier_2", 1],
			["nr_temerian_soldier_3", 1],
			["nr_stripes_scout", 1],
			["nr_temerian_drummer", 1],
			["nr_foltest_pride", 1],
			["nr_queen_adalia", 1],
			["nr_mage_infiltrator", 1],
			["nr_aretuza_adept", 1]
		]
	},
	{
		"title": "北方领域 - 科德温与亚甸",
		"description": "以科德温和亚甸卡牌为核心的北方领域卡组 - 打法：攻城单位、士气鼓舞、紧密羁绊",
		"leader": "nr_foltest_siegemaster",
		"faction": "realms",
		"cards": [
			["spe_horn", 2],
			["spe_decoy", 2],
			["spe_fog", 1],
			["spe_clear", 1],
			["spe_scorch", 2],
			["nr_stennis", 1],
			["nr_vandergrift", 1],
			["nr_kaedweni_siege_support_1", 1],
			["nr_kaedweni_siege_support_2", 1],
			["nr_catapult_1", 1],
			["nr_catapult_2", 1],
			["nr_henselt", 1],
			["nr_kaedweni_reinforcement", 1],
			["nr_reinforced_ballista_1", 1],
			["nr_reinforced_ballista_2", 1],
			["nr_reinforced_trebuchet_1", 1],
			["nr_reinforced_trebuchet_2", 1],
			["nr_banner_nurse", 1],
			["nr_ban_ard_tutor", 1],
			["nr_demavend", 1],
			["nr_kaedweni_knight", 1],
			["nr_dun_banner_heavy_cavalry_1", 1],
			["nr_dun_banner_heavy_cavalry_2", 1],
			["nr_odrin", 1],
			["nr_seltkirk", 1],
			["nr_kaedweni_sergeant", 1],
			["nr_dethmold", 1]
		]
	},
	{
		"title": "北方领域 - 辛特拉与邻国",
		"description": "以辛特拉及周边小国卡牌为核心的北方领域卡组 - 打法：召唤复仇者、辛特拉大屠杀、集结",
		"leader": "nr_queen_calanthe",
		"faction": "realms",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_storm", 1],
			["spe_clear", 1],
			["spe_scorch", 1],
			["spe_slaughther_cintra_1", 1],
			["spe_slaughther_cintra_2", 1],
			["nr_viraxas", 1],
			["nr_kerack_fleet_marine_2", 1],
			["nr_kerack_fleet_frigate", 1],
			["nr_kerack_fleet_marine_1", 1],
			["nr_vissegerd", 1],
			["nr_cintrian_royal_guard", 1],
			["nr_eist_tuirseach", 1],
			["nr_skellige_fleet_1", 1],
			["nr_skellige_fleet_2", 1],
			["nr_skellige_fleet_3", 1],
			["nr_cintrian_knight", 1],
			["nr_roegner", 1],
			["nr_pavetta", 1],
			["nr_kistrin_verden", 1],
			["nr_sha", 1],
			["nr_kraken", 1],
			["nr_egmund", 1],
			["nr_eylembert_tigg", 1],
			["nr_young_ciri", 1],
			["ntr_ciri", 1],
			["nr_cintrian_peasants", 1],
			["nr_windhalm", 1]
		]
	},
	{
		"title": "北方领域 - 瑞达尼亚",
		"description": "以瑞达尼亚卡牌为核心的北方领域卡组 - 打法：医疗兵、高战力单位、指挥官之角",
		"leader": "nr_radovid_ruthless",
		"faction": "realms",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_rain", 1],
			["spe_clear", 1],
			["spe_scorch", 1],
			["nr_redanian_elite", 1],
			["nr_donimir_troy", 1],
			["nr_joachim_gratz", 1],
			["nr_philippa", 1],
			["nr_ewald_borsodi", 1],
			["nr_flying_redanian", 1],
			["nr_redanian_knight", 1],
			["nr_shani", 1],
			["nr_milo_vanderbeck", 1],
			["nr_marching_orders", 1],
			["nr_eyck_denesle", 1],
			["nr_radovid_royal_guards", 1],
			["nr_redanian_archer", 1],
			["nr_trollololo", 1],
			["nr_battering_ram", 1],
			["nr_dijkstra", 1],
			["nr_falibor", 1],
			["nr_siegfried", 1],
			["nr_reinforced_tower", 1],
			["nr_crinfrid_1", 1],
			["nr_crinfrid_2", 1],
			["nr_crinfrid_3", 1],
			["nr_voymir", 1],
			["nr_reaver_scout", 1],
			["nr_tridam_infantry", 1]
		]
	},
	{
		"title": "尼弗迦德帝国 - 军团",
		"description": "以尼弗迦德军团卡牌为核心的尼弗迦德帝国卡组 - 打法：紧密羁绊、英雄、医疗兵、指挥官之角",
		"leader": "ne_emhyr_relentless",
		"faction": "nilfgaard",
		"cards": [
			["spe_fog", 1],
			["spe_decoy", 2],
			["spe_rain", 1],
			["spe_clear", 2],
			["spe_scorch", 2],
			["ne_vicovaro_medic", 1],
			["ne_nauzicaa_1", 1],
			["ne_nauzicaa_2", 1],
			["ne_nauzicaa_3", 1],
			["ne_shilard", 1],
			["ne_alba_pikeman_1", 1],
			["ne_archer_support", 1],
			["ne_archer_support_1", 1],
			["ne_nausicaa_brigade", 1],
			["ne_imperial_golem", 1],
			["ne_daerlan_soldier", 1],
			["ne_hefty_helge", 1],
			["ne_heavy_zerri", 1],
			["ne_slave_infantry_1", 1],
			["ne_slave_infantry_2", 1],
			["ne_magne_division", 1],
			["ne_emissary", 1],
			["ne_alba_spearman", 1],
			["ne_standard_bearer", 1],
			["ne_black_archer", 1],
			["ne_black_archer_1", 1],
			["ne_deithwen_arbalest", 1],
			["ne_guardian", 1],
			["ne_siege_support", 1],
			["ne_nausicaa_standard_bearer", 1],
			["ne_knight", 1],
			["ne_alba_armored_cavalry", 1],
			["ne_menno", 1]
			
		]
	},
	{
		"title": "尼弗迦德帝国 - 贵族",
		"description": "以尼弗迦德贵族与显贵卡牌为核心的尼弗迦德帝国卡组 - 打法：紧密羁绊、间谍",
		"leader": "ne_emhyr_emperor",
		"faction": "nilfgaard",
		"cards": [
			["spe_fog", 2],
			["spe_horn", 2],
			["spe_clear", 2],
			["spe_scorch", 1],
			["ne_impera_brigade_1", 1],
			["ne_impera_brigade_2", 1],
			["ne_impera_brigade_3", 1],
			["ne_impera_brigade_4", 1],
			["ne_impera_brigade_5", 1],
			["ne_jan_calveit", 1],
			["ne_vattier", 1],
			["ne_letho", 1],
			["ne_bribery", 1],
			["ne_moorvran", 1],
			["ne_fringilla", 1],
			["ne_fergus_emreis",1],
			["ne_young_emissary_1", 1],
			["ne_young_emissary_2", 1],
			["ne_cahir", 1],
			["ne_stefan", 1],
			["ne_usurper", 1],
			["ne_cantarella", 1],
			["ne_assire", 1],
			["ne_treason", 1],
			["ne_peter_saar_gwynleve", 1],
			["ne_xarthisius", 1],
			["ne_impera_enforcers", 1],
			["ne_imperial_diviner", 1],
			["ne_renuald", 1]
		]
	},
	{
		"title": "尼弗迦德帝国 - 第二军团",
		"description": "以其他军团单位卡牌为核心的尼弗迦德帝国卡组 - 打法：集结",
		"leader": "ne_emhyr_invader_of_the_north",
		"faction": "nilfgaard",
		"cards": [
			["spe_rain", 1],
			["spe_fog", 1],
			["spe_horn", 2],
			["spe_clear", 1],
			["spe_scorch", 1],
			["spe_decoy", 1],
			["ne_tibor", 1],
			["ne_ardal_aep_dahy", 1],
			["ne_glynnis_loernach", 1],
			["ne_ard_feainn_crossbowman", 1],
			["ne_ard_feainn_light_cavalry", 3],
			["ne_ard_feainn_tortoise", 3],
			["ne_ard_feainn_heavy_cavalry", 1],
			["ne_ramon_tyrconnel", 1],
			["ne_ffion_gaernel", 1],
			["ne_vrygheff", 1],
			["ne_epidemic", 1],
			["ne_rot_tosser", 1],
			["ne_traheaern_vdyffir", 1],
			["ne_vreemde", 1],
			["ne_spotter", 1],
			["ne_illusionist", 1],
			["ne_mangonel", 1],
			["ne_joachim_de_wett", 1],
			["ne_imperial_practitioner", 1]
		]
	},
	{
		"title": "怪物 - 狂猎与巨人",
		"description": "以狂猎和巨人卡牌为核心的怪物卡组 - 打法：集结、高战力单位",
		"leader": "mo_eredin_bringer_of_death",
		"faction": "monsters",
		"cards": [
			["spe_fog", 2],
			["spe_decoy", 2],
			["spe_clear", 1],
			["spe_scorch", 2],
			["spe_horn", 1],
			["mo_witch_velen", 1],
			["mo_witch_velen_1", 1],
			["mo_witch_velen_2", 1],
			["mo_golem", 1],
			["mo_geels", 1],
			["mo_ifrit_1", 1],
			["mo_ifrit_2", 1],
			["mo_fire_elemental", 1],
			["mo_wild_hunt_rider_1", 1],
			["mo_wild_hunt_rider_2", 1],
			["mo_wild_hunt_rider_3", 1],
			["mo_nithral", 1],
			["mo_therazane", 1],
			["mo_naglfar", 1],
			["mo_caranthir", 1],
			["mo_jotunn", 1],
			["mo_frost_giant", 1],
			["mo_imlerith", 1],
			["mo_old_speartip", 1],
			["mo_navigator", 1],
			["mo_cyclops", 1],
			["mo_ice_troll", 1],
			["mo_earth_elemental", 1]
		]
	},
	{
		"title": "怪物 - 野兽与生物",
		"description": "以各种野兽与生物卡牌为核心的怪物卡组 - 打法：集结",
		"leader": "mo_eredin_commander",
		"faction": "monsters",
		"cards": [
			["spe_rain", 2],
			["spe_decoy", 1],
			["spe_clear", 1],
			["spe_scorch", 1],
			["spe_horn", 2],
			["mo_morvudd", 1],
			["mo_fleder", 1],
			["mo_garkain", 1],
			["mo_ekkima", 1],
			["mo_bruxa", 1],
			["mo_katakan", 1],
			["mo_ghoul", 1],
			["mo_ghoul_1", 1],
			["mo_ghoul_2", 1],
			["mo_kayran", 1],
			["mo_lamia_1", 1],
			["mo_lamia_2", 1],
			["mo_lamia_3", 1],
			["mo_glustyworp", 1],
			["mo_alghoul", 1],
			["mo_archgriffin", 1],
			["mo_alp", 1],
			["mo_toad", 1],
			["mo_arachas", 1],
			["mo_arachas_1", 1],
			["mo_arachas_2", 1],
			["mo_arachas_behemoth", 1],
			["mo_armoured_arachas", 1],
			["mo_leshen", 1],
			["mo_dragon_fyresdal", 1],
			["mo_manticore", 1],
			["mo_manticore_venom", 1]
		]
	},
	{
		"title": "松鼠党 - 突击队",
		"description": "以突击队单位为核心的松鼠党卡组 - 打法：集结、医疗兵",
		"leader": "sc_francesca_daisy",
		"faction": "scoiatael",
		"cards": [
			["spe_rain", 1],
			["spe_decoy", 2],
			["spe_clear", 1],
			["spe_scorch", 1],
			["spe_horn", 2],
			["sc_elven_mercenary_1", 1],
			["sc_elven_mercenary_2", 1],
			["sc_vrihedd_sapper", 1],
			["sc_havekar_nurse", 1],
			["sc_havekar_nurse_1", 1],
			["sc_havekar_nurse_2", 1],
			["sc_iorveth", 1],
			["sc_vrihedd_dragoon_1", 1],
			["sc_vrihedd_dragoon_2", 1],
			["sc_vrihedd_dragoon_3", 1],
			["sc_isengrim", 1],
			["sc_vrihedd_brigade", 1],
			["sc_vrihedd_brigade_1", 1],
			["sc_havekar_support", 1],
			["sc_havekar_support_1", 1],
			["sc_havekar_support_2", 1],
			["sc_aelirenn", 1],
			["sc_saesenthessis_saskia", 1],
			["sc_saesenthessis_dragon", 1],
			["sc_neophyte", 1],
			["sc_yaevinn", 1],
			["sc_vrihedd_officer", 1]
		]
	},
	{
		"title": "松鼠党 - 独立领地",
		"description": "以非人类领地（如多爾布萊坦納、玛哈坎或布洛克莱昂）为核心的松鼠党卡组 - 打法：集结、士气鼓舞",
		"leader": "sc_francesca_beautiful",
		"faction": "scoiatael",
		"cards": [
			["spe_rain", 1],
			["spe_frost", 1],
			["spe_decoy", 1],
			["spe_clear", 1],
			["spe_scorch", 2],
			["spe_horn", 1],
			["sc_eithne", 1],
			["sc_barclay", 1],
			["sc_dol_blathanna_sentry", 1],
			["sc_milva", 1],
			["sc_dryads_1", 1],
			["sc_dryads_2", 1],
			["sc_dryads_3", 1],
			["sc_dryads_4", 1],
			["sc_brouver_hoog", 1],
			["sc_dol_blathanna_guard_1", 1],
			["sc_dol_blathanna_guard_2", 1],
			["sc_dol_blathanna_guard_3", 1],
			["sc_aglais", 1],
			["sc_elven_deadeye", 1],
			["sc_morenn", 1],
			["sc_mahakam_pyrotechnician", 1],
			["sc_mahakam_guard_1", 1],
			["sc_mahakam_guard_2", 1],
			["sc_mahakam_ale", 1],
			["sc_yannick_brass", 1],
			["sc_dol_blathanna_trapper", 1],
			["sc_gabor_zigrin", 1]
		]
	},
	{
		"title": "史凯利格 - 大史凯利格与斯瓦勃罗德",
		"description": "以大史凯利格和斯瓦勃罗德教派卡牌为核心的史凯利格卡组 - 打法：狂战士、集结、紧密羁绊",
		"leader": "sk_crach_an_craite",
		"faction": "skellige",
		"cards": [
			["spe_storm", 1],
			["spe_mardroeme", 3],
			["spe_decoy", 2],
			["spe_clear", 1],
			["spe_scorch", 1],
			["spe_horn", 1],
			["sk_blueboy", 1],
			["sk_hjalmar", 1],
			["sk_vabjorn", 1],
			["sk_young_berserker", 3],
			["sk_shield_maiden_1", 1],
			["sk_shield_maiden_2", 1],
			["sk_shield_maiden_3", 1],
			["sk_an_craite_greatsword", 1],
			["sk_drummond_warmonger", 1],
			["sk_madman_lugos", 1],
			["sk_harald_cripple", 1],
			["sk_craite_warrior_1", 1],
			["sk_craite_warrior_2", 1],
			["sk_craite_warrior_3", 1],
			["sk_cerys", 1],
			["sk_ermion", 1],
			["sk_svalblod_fanatic", 1],
			["sk_berserker", 1],
			["sk_drummond_berserker", 1],
			["sk_svalblod", 1],
			["sk_chosen_berserker", 1]
		]
	},
	{
		"title": "史凯利格 - 小岛",
		"description": "以其他岛屿卡牌为核心的史凯利格卡组 - 打法：集结、紧密羁绊、医疗兵",
		"leader": "sk_king_bran",
		"faction": "skellige",
		"cards": [
			["spe_frost", 3],
			["spe_decoy", 2],
			["spe_scorch", 2],
			["spe_horn", 2],
			["sk_olaf", 1],
			["sk_birna", 1],
			["sk_war_longship_1", 1],
			["sk_war_longship_2", 1],
			["sk_war_longship_3", 1],
			["sk_dimun_pirate_captain", 1],
			["sk_vigi_loon", 1],
			["sk_light_longship", 3],
			["sk_brokva_archer", 2],
			["sk_tuirseach_warrior_1", 1],
			["sk_tuirseach_warrior_2", 1],
			["sk_heymaey_flaminica", 1],
			["sk_eist_tuirseach", 1],
			["sk_kambi", 1],
			["sk_arnjolf", 1],
			["sk_otkell", 1],
			["sk_dagur", 1],
			["sk_sigrdrifa", 1],
			["sk_dimun_pirate", 1],
			["sk_jutta", 1],
			["sk_hemdall", 1]
		]
	},
	{
		"title": "猎魔人宇宙 - 战士与法师",
		"description": "以著名战士与法师卡牌为核心的猎魔人宇宙卡组 - 打法：集结、医疗兵",
		"leader": "wu_vilgefortz_magician_kovir",
		"faction": "witcher_universe",
		"cards": [
			["spe_frost", 1],
			["spe_fog", 1],
			["spe_decoy", 1],
			["spe_clear", 1],
			["spe_scorch", 1],
			["spe_horn", 1],
			["wu_tissaia", 1],
			["wu_rats_giselher", 1],
			["wu_rats_asse", 1],
			["wu_rats_iskra", 1],
			["wu_rats_kayleigh", 1],
			["wu_rats_mistle", 1],
			["wu_rats_reef", 1],
			["wu_ralf_blunden", 1],
			["wu_bomb_heaver", 1],
			["wu_gascon_light_cavalry", 1],
			["wu_gascon_slinger", 1],
			["wu_gascon_infiltrator", 1],
			["wu_gascon", 1],
			["wu_dorregaray", 1],
			["wu_ortolan", 1],
			["wu_coral", 1],
			["wu_leo_bonhart", 1],
			["wu_azar_javed", 1],
			["wu_strays_spalla", 1],
			["wu_gerhart_aelle", 1],
			["wu_lydia_bredevoort", 1],
			["wu_dana_meadbh", 1],
			["wu_rience", 1],
			["wu_visenna", 1],
			["wu_operator",1]
		]
	},
	{
		"title": "猎魔人宇宙 - 猎魔人",
		"description": "以猎魔人学派卡牌为核心的猎魔人宇宙卡组 - 打法：猎魔人学派、坚韧、焦炎",
		"leader": "wu_cosimo_malaspina",
		"faction": "witcher_universe",
		"cards": [
			["wu_coen", 1],
			["wu_stygga_castle", 1],
			["wu_vesemir", 1],
			["wu_haern_caduch", 1],
			["wu_ivo_belhaven", 1],
			["wu_lambert", 1],
			["wu_keldar", 1],
			["wu_ivar", 1],
			["wu_gorthur_gvaed", 1],
			["wu_kaer_morhen", 1],
			["wu_kaer_seren", 1],
			["wu_gezras", 1],
			["wu_geralt_1", 1],
			["wu_gaetan", 1],
			["wu_brehen", 1],
			["wu_gerd", 1],
			["wu_warrit", 1],
			["wu_erland", 1],
			["wu_arnaghad", 1],
			["wu_letho", 1],
			["wu_eskel", 1],
			["wu_kolgrim", 1],
			["spe_sign_igni", 2],
			["spe_sign_quen", 2],
			["spe_sign_axii", 2],
			["spe_sign_aard", 2],
			["spe_sign_yrden", 2],
			["wu_swallow_potion", 1],
		]
	},
	{
		"title": "猎魔人宇宙 - 恶魔与生物",
		"description": "以恶魔与珍稀生物卡牌为核心的猎魔人宇宙卡组 - 打法：集结、焦炎、间谍",
		"leader": "wu_alzur_maker",
		"faction": "witcher_universe",
		"cards": [
			["spe_horn", 1],
			["spe_sign_yrden", 1],
			["spe_rain", 1],
			["spe_decoy", 2],
			["spe_scorch", 2],
			["spe_clear", 1],
			["wu_doppler_1", 1],
			["ntr_gaunter_odimm_darkness", 3],
			["ntr_gaunter_odimm", 1],
			["wu_idr", 1],
			["wu_iris_von_everec", 1],
			["wu_sarah", 1],
			["wu_djinn", 1],
			["wu_myrgtabrakke", 1],
			["wu_vincent_meis", 1],
			["wu_raging_bear", 1],
			["wu_iris_companions_1", 1],
			["wu_iris_companions_2", 1],
			["wu_vlodimir_von_everec", 1],
			["wu_phoenix", 1],
			["wu_boris", 1],
			["ntr_olgierd", 1],
			["wu_marlene_trastamara", 1],
			["wu_idarran_ulivo", 1],
			["wu_mad_kiyan", 1],
			["wu_cicada", 1],
			["wu_nivellen", 1]
			
		]
	},
	{
		"title": "猎魔人宇宙 - 杰洛特与朋友",
		"description": "以杰洛特及其朋友卡牌为核心的猎魔人宇宙卡组 - 打法：集结、召唤复仇者、医疗兵",
		"leader": "wu_vilgefortz_sorcerer",
		"faction": "witcher_universe",
		"cards": [
			["spe_horn", 1],
			["spe_sign_aard", 1],
			["spe_rain", 1],
			["spe_fog", 1],
			["spe_clear", 1],
			["wu_doppler_2", 1],
			["wu_pellar", 1],
			["ntr_yennefer", 1],
			["ntr_geralt", 1],
			["wu_kelpie", 1],
			["wu_vysogota", 1],
			["wu_angouleme", 1],
			["wu_tea_vea_1", 1],
			["wu_tea_vea_2", 1],
			["wu_iola", 1],
			["ntr_villen", 1],
			["wu_rhapsodic_melody", 1],
			["ntr_mysterious_elf", 1],
			["ntr_zoltan", 1],
			["ntr_triss", 1],
			["wu_nenneke", 1],
			["wu_roach", 1],
			["ntr_dandelion", 1],
			["ntr_emiel", 1],
			["ntr_ciri", 1],
			["ntr_vesemir", 1],
			["wu_kalkstein", 1]
		]
	},
	{
		"title": "陶森特 - 骑士与贵族",
		"description": "以骑士与贵族卡牌为核心的陶森特卡组 - 打法：紧密羁绊、集结、高战力单位",
		"leader": "to_anna_henrietta_duchess",
		"faction": "toussaint",
		"cards": [
			["spe_horn", 2],
			["spe_toussaint_wine", 1],
			["spe_rain", 1],
			["spe_frost", 1],
			["spe_clear", 1],
			["spe_scorch", 1],
			["spe_decoy", 1],
			["to_dun_tynne_infantry", 1],
			["to_champion", 1],
			["to_panther_1", 1],
			["to_panther_2", 1],
			["to_panther_3", 1],
			["to_knight_errant_1", 1],
			["to_knight_errant_2", 1],
			["to_knight_errant_3", 1],
			["to_damien_tour", 1],
			["to_gregoire_gorgon", 1],
			["to_lady_lake", 1],
			["to_jousting_champion", 1],
			["to_guillaume", 1],
			["to_artorius_vigo", 1],
			["to_fringilla_vigo", 1],
			["to_beauclair_cavalry_1", 1],
			["to_beauclair_cavalry_2", 1],
			["to_milton", 1],
			["to_palmerin", 1],
			["to_vivienne_oriole", 1],
			["to_syanna", 1],
			["to_fisher_king", 1]
		]
	},
	{
		"title": "陶森特 - 怪物",
		"description": "以吸血鬼及其他怪物卡牌为核心的陶森特卡组 - 打法：集结、高战力单位",
		"leader": "to_anna_henrietta_ladyship",
		"faction": "toussaint",
		"cards": [
			["spe_horn", 1],
			["spe_toussaint_wine", 2],
			["spe_rain", 1],
			["spe_clear", 2],
			["spe_scorch", 1],
			["to_protofleder", 1],
			["to_dettlaff_higher_vampire", 1],
			["to_barghest_1", 1],
			["to_barghest_2", 1],
			["to_barghest_3", 1],
			["to_cloud_giant", 1],
			["to_garkain", 1],
			["to_wolves_1", 1],
			["to_wolves_2", 1],
			["to_yghern", 1],
			["to_unseen_elder", 1],
			["to_alpha_garkain", 1],
			["to_archespore", 1],
			["to_dettlaff", 1],
			["to_dettlaff_ghastly_beast", 1],
			["to_bruxa_corvo_bianco", 1],
			["to_orianna", 1],
			["to_lacerate", 1],
			["to_fleder", 1],
			["to_golyat", 1],
			["to_tufo_monster", 1],
			["to_shaelmaar", 1]
		]
	},
	{
		"title": "莱里亚与利维亚 - 前锋",
		"description": "以前锋（近战/远程）卡牌为核心的莱里亚与利维亚卡组 - 打法：集结、医疗兵",
		"leader": "lr_meve_princess",
		"faction": "lyria_rivia",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 1],
			["spe_rain", 1],
			["spe_clear", 2],
			["spe_scorch", 1],
			["lr_rivian_mauler", 1],
			["lr_grey_rider", 2],
			["lr_prince_anseis", 1],
			["lr_royal_guard", 1],
			["lr_landsknecht", 3],
			["lr_knighthood", 1],
			["lr_reynard_odo", 1],
			["lr_war_wagon", 1],
			["lr_wagenburg", 3],
			["lr_gascon", 1],
			["lr_pikeman", 1],
			["lr_light_cavalry", 2],
			["lr_rayla", 1],
			["lr_wagon", 1],
			["lr_lyrian_cavalry", 1],
			["lr_isbel_hagge", 1],
			["lr_hajduk", 1],
			["ntr_geralt", 1],
			["spe_wyvern_shield", 1],
			["spe_mantlet", 1]
		]
	},
	{
		"title": "莱里亚与利维亚 - 后卫",
		"description": "以后卫（远程/攻城）卡牌为核心的莱里亚与利维亚卡组 - 打法：焦炎、间谍、医疗兵",
		"leader": "lr_meve_white_queen",
		"faction": "lyria_rivia",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 1],
			["spe_frost", 2],
			["spe_clear", 1],
			["spe_scorch", 1],
			["spe_garrison", 1],
			["lr_piercing_missile", 1],
			["lr_eavesdrop", 1],
			["lr_trebuchet", 1],
			["lr_arbalest", 3],
			["lr_spellweaver", 1],
			["lr_forager", 1],
			["lr_sapper", 1],
			["lr_villem", 1],
			["lr_scout", 1],
			["lr_winch", 1],
			["lr_banner", 1],
			["lr_scytheman_2", 1],
			["lr_scytheman_3", 1],
			["lr_caldwell", 1],
			["lr_physician", 1],
			["lr_pyrokinesis", 1],
			["lr_carroballista", 1],
			["lr_artificer", 1],
			["lr_siege", 1],
			["lr_onager", 1]
		]
	},
	{
		"title": "辛迪加 - 永恒圣火教会",
		"description": "以永恒圣火教会卡牌为核心的辛迪加卡组 - 打法：猎巫、集结、二聚魔法",
		"leader": "sy_cyrus_hemmelfart",
		"faction": "syndicate",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_rain", 1],
			["spe_clear", 1],
			["spe_dimeritium_shackles", 2],
			["sy_flaming_rose_footman", 1],
			["sy_witch_hunter", 1],
			["sy_witch_hunter_executioner", 1],
			["sy_eternal_fire_inquisitor", 1],
			["sy_caleb_menge", 1],
			["sy_moreelse", 1],
			["sy_jacques_aldersberg", 1],
			["sy_temple_guard", 1],
			["sy_roderick_wett", 1],
			["sy_ulrich", 1],
			["sy_inquisitional_pyres", 1],
			["sy_walter_veritas", 1],
			["sy_eternal_fire_priest_1", 1],
			["sy_eternal_fire_priest_2", 1],
			["sy_eternal_fire_priest_3", 1],
			["sy_octavia_hale", 1],
			["sy_fabian_hale", 1],
			["sy_ignatius_hale", 1],
			["sy_cleric_flaming_rose", 1],
			["sy_eternal_fire_disciple", 2],
			["sy_lonely_champion", 1],
			["sy_inquisitor_helveed", 1]
		]
	},
	{
		"title": "辛迪加 - 萨拉曼德拉",
		"description": "以萨拉曼德拉组织卡牌为核心的辛迪加卡组 - 打法：集结、焦炎、召唤复仇者",
		"leader": "sy_azar_javed",
		"faction": "syndicate",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_rain", 1],
			["spe_clear", 1],
			["spe_scorch", 2],
			["sy_greater_brothers", 1],
			["sy_mutant_killer", 1],
			["sy_mutated_hound_1", 1],
			["sy_mutated_hound_2", 1],
			["sy_mutant_maker", 1],
			["sy_fisstech_trafficker", 1],
			["sy_fisstech", 1],
			["sy_professor", 1],
			["sy_salamandra_assassin", 1],
			["sy_salamandra_assassin_2", 1],
			["sy_savolla", 1],
			["sy_fallen_rayla", 1],
			["sy_gellert_bleinheim", 1],
			["sy_roland_bleinheim", 1],
			["sy_salamandra_lackey", 1],
			["sy_mutant", 3],
			["sy_salamandra_mage", 1],
			["sy_failed_experiment", 1],
			["sy_frightener", 1],
			["sy_stolen_mutagens", 1]
		]
	},
	{
		"title": "辛迪加 - 诺维格瑞帮派",
		"description": "以诺维格瑞各帮派卡牌为核心的辛迪加卡组 - 打法：间谍、紧密羁绊、集结",
		"leader": "sy_cyprian_wiley",
		"faction": "syndicate",
		"cards": [
			["spe_horn", 1],
			["spe_rain", 1],
			["spe_clear", 1],
			["spe_scorch", 2],
			["spe_vivaldi_bank", 2],
			["sy_bare_knuckle_brawler", 1],
			["sy_casino_bouncers", 1],
			["sy_cleaver_gang_1", 1],
			["sy_cleaver_gang_2", 1],
			["sy_cleaver_gang_3", 1],
			["sy_cleaver_gang_4", 1],
			["sy_robber_1", 1],
			["sy_robber_2", 1],
			["sy_robber_3", 1],
			["sy_igor_hook", 1],
			["sy_ferko", 1],
			["sy_hvitr_aelydia", 1],
			["sy_bincy_blumerholdt", 1],
			["sy_freak_show_1", 1],
			["sy_freak_show_2", 1],
			["sy_freak_show_3", 1],
			["sy_freak_show_4", 1],
			["sy_beggar", 1],
			["sy_whoreson_senior", 1],
			["sy_imke", 1],
			["sy_sly_seductress", 1],
			["sy_madame_luiza", 1],
			["sy_rico_meiersdorf", 1],
			["sy_sewer_raider", 1],
			["sy_boris", 1]
		]
	},
	{
		"title": "泽瑞坎尼亚 - 巨龙教派",
		"description": "以巨龙及其朝拜者卡牌为核心的泽瑞坎尼亚卡组 - 打法：朝拜者 / 被朝拜",
		"leader": "ze_zerrikanterment",
		"faction": "zerrikania",
		"cards": [
			["spe_horn", 1],
			["spe_decoy", 2],
			["spe_dragon_wrath", 1],
			["spe_tse_tse_flies", 1],
			["spe_clear", 1],
			["spe_scorch", 1],
			["ze_villentretenmerth", 1],
			["ze_myrgtabrakke", 1],
			["ze_merineaevelth", 1],
			["ze_ocvist", 1],
			["ze_keltullis", 1],
			["ze_ostreverg", 1],
			["ze_germinus", 1],
			["ze_first_faithel_kia", 1],
			["ze_tea_vea_1", 1],
			["ze_tea_vea_2", 1],
			["ze_faithel_1", 1],
			["ze_faithel_2", 1],
			["ze_faithel_3", 1],
			["ze_balladeer", 1],
			["ze_tiger_1", 1],
			["ze_tiger_2", 1],
			["ze_yellow_witch_korath", 1],
			["ze_emetouka", 1],
			["ze_dragon_priestess_lua", 1],
			["ze_high_priestess_nia", 1],
			["ze_apucunpture_healer", 1],
			["ze_collective_trance", 1],
		]
	},
	{
		"title": "泽瑞坎尼亚 - 军团",
		"description": "以战斗单位与生物卡牌为核心的泽瑞坎尼亚卡组 - 打法：激励、焦炎、高战力单位",
		"leader": "ze_rarog",
		"faction": "zerrikania",
		"cards": [
			["spe_horn", 2],
			["spe_decoy", 1],
			["spe_giant_spider_web", 2],
			["spe_clear", 1],
			["spe_scorch", 1],
			["ze_hippotoxotai_1", 1],
			["ze_hippotoxotai_2", 1],
			["ze_hippotoxotai_3", 1],
			["ze_azar_javed", 1],
			["ze_bomb_maker_1", 1],
			["ze_giant_spotted_spider", 1],
			["ze_free_warrior_1", 1],
			["ze_free_warrior_2", 1],
			["ze_free_warrior_3", 1],
			["ze_free_warrior_4", 1],
			["ze_free_warrior_5", 1],
			["ze_heavy_fire_scorpion", 1],
			["ze_skuda_amazon_1", 1],
			["ze_skuda_amazon_2", 1],
			["ze_behemoth", 1],
			["ze_war_elephant", 1],
			["ze_sandworm", 1],
			["ze_alchemist", 1],
			["ze_lilit_niya", 1],
			["ze_myrgot", 1],
			["ze_venomous_basilisk", 1],
			["ze_saulrenith", 1],
		]
	}
];

var premade_deck = custom_decks;

var deckWeightConsts = {
	"spyBase": 20,
	"heroMult": 2,
	"musterMult": 2,
	"tightBondMult": 2,
	"medic": 7,
	"scorch": 5,
	"scorch_c": 5,
	"morale": 5,
	"agile": 2,
	"horn": 10,
	"berserker": 5,
	"mardroeme": 5,
	"avenger": 5,
	"decoy": 7,
	"clearWeatherWeight": 7,
	"heroSpyBase": 5,
	"cintra_slaughter": 5,
	"resilience": 5,
	"witcherSchoolWeight": 1,
	"witch_hunt": 5,
	"whorshipper": 2,
	"whorshipped": 2,
	"inspire": 3
};

function calcDeckWeight(deck) {
	var total = 0;
	deck.cards.forEach(entry => {
		let c = card_dict[entry[0]];
		let cnt = parseInt(entry[1]);
		let abi = c["ability"].split(" ");
		let cStr = 0;
		if (!c["deck"].startsWith("special") && !c["deck"].startsWith("weather")) {
			if (abi.includes("spy")) {
				cStr = deckWeightConsts["spyBase"] - parseInt(c["strength"]);
				if (abi.includes("hero")) cStr += deckWeightConsts["heroSpyBase"];
				if (c.row === "agile") cStr += deckWeightConsts["agile"];
			} else {
				cStr = parseInt(c["strength"]);
				if (abi.includes("hero")) cStr *= deckWeightConsts["heroMult"];
				if (abi.includes("bond")) cStr *= deckWeightConsts["tightBondMult"];
				if (abi.includes("muster")) cStr *= deckWeightConsts["musterMult"];
				abi.forEach(a => {
					if (a in deckWeightConsts) cStr += deckWeightConsts[a];
				});
				if (
					abi.includes("witcher_wolf_school") ||
					abi.includes("witcher_bear_school") ||
					abi.includes("witcher_viper_school") ||
					abi.includes("witcher_cat_school") ||
					abi.includes("witcher_griffin_school")
				) cStr += deckWeightConsts["witcherSchoolWeight"];
				if (c.row === "agile") cStr += deckWeightConsts["agile"];
			}
		}
		total += (cStr*cnt);
	});
	return total;
}